import type { AxeViolation, ScanResult } from "./lib/scan";

export type FailOn = "none" | "minor" | "moderate" | "serious" | "critical";

export type SeverityCounts = {
  critical: number;
  serious: number;
  moderate: number;
  minor: number;
};

export const ACTION_JSON_FILENAME = "accesslint-report.json";
export const ACTION_MARKDOWN_FILENAME = "accesslint-summary.md";

const FAIL_ON_ORDER: Record<Exclude<FailOn, "none">, number> = {
  minor: 1,
  moderate: 2,
  serious: 3,
  critical: 4,
};

const IMPACT_ORDER: Record<string, number> = {
  critical: 4,
  serious: 3,
  moderate: 2,
  minor: 1,
};

export function parseFailOn(value: string): FailOn {
  const normalized = value.trim().toLowerCase();
  return normalized === "none" ||
    normalized === "minor" ||
    normalized === "moderate" ||
    normalized === "serious" ||
    normalized === "critical"
    ? normalized
    : "serious";
}

export function parseBooleanInput(value: string | undefined, fallback: boolean) {
  if (!value) return fallback;
  const normalized = value.trim().toLowerCase();
  if (normalized === "true" || normalized === "1" || normalized === "yes") return true;
  if (normalized === "false" || normalized === "0" || normalized === "no") return false;
  return fallback;
}

export function countSeverities(violations: AxeViolation[]): SeverityCounts {
  return violations.reduce<SeverityCounts>(
    (counts, violation) => {
      const impact = normalizeImpact(violation.impact);
      counts[impact] += 1;
      return counts;
    },
    {
      critical: 0,
      serious: 0,
      moderate: 0,
      minor: 0,
    },
  );
}

export function thresholdExceeded(violations: AxeViolation[], failOn: FailOn) {
  if (failOn === "none") return false;
  const threshold = FAIL_ON_ORDER[failOn];
  return violations.some((violation) => IMPACT_ORDER[normalizeImpact(violation.impact)] >= threshold);
}

export function renderMarkdownReport(input: {
  url: string;
  finalUrl: string;
  score: number;
  failOn: FailOn;
  counts: SeverityCounts;
  thresholdExceeded: boolean;
  result: ScanResult;
}) {
  const topViolations = [...input.result.violations]
    .sort(
      (a, b) =>
        IMPACT_ORDER[normalizeImpact(b.impact)] - IMPACT_ORDER[normalizeImpact(a.impact)] ||
        a.help.localeCompare(b.help),
    )
    .slice(0, 10);

  const lines = [
    "# AccessLint scan summary",
    "",
    `- URL: ${input.url}`,
    `- Final URL: ${input.finalUrl}`,
    `- Accessibility score: ${input.score}/100`,
    `- Total risks: ${input.result.violations.length}`,
    `- Fail threshold: ${input.failOn}`,
    `- Threshold exceeded: ${input.thresholdExceeded ? "yes" : "no"}`,
    "",
    "## Severity breakdown",
    "",
    `- Critical: ${input.counts.critical}`,
    `- Serious: ${input.counts.serious}`,
    `- Moderate: ${input.counts.moderate}`,
    `- Minor: ${input.counts.minor}`,
    "",
    "## Top risks",
    "",
  ];

  if (topViolations.length === 0) {
    lines.push("No accessibility risks were detected by the automated scan.");
  } else {
    for (const violation of topViolations) {
      lines.push(
        `- **${normalizeImpact(violation.impact)}** ${violation.help} (${violation.nodes.length} node${violation.nodes.length === 1 ? "" : "s"})`,
      );
    }
  }

  lines.push(
    "",
    "_Generated by AccessLint v1 from a11ymind. This is an automated CI scan, not a legal certification or full manual audit._",
  );

  return lines.join("\n");
}

export function buildJsonReport(input: {
  url: string;
  finalUrl: string;
  score: number;
  failOn: FailOn;
  counts: SeverityCounts;
  thresholdExceeded: boolean;
  result: ScanResult;
}) {
  return {
    url: input.url,
    finalUrl: input.finalUrl,
    score: input.score,
    failOn: input.failOn,
    thresholdExceeded: input.thresholdExceeded,
    summary: {
      totalRisks: input.result.violations.length,
      critical: input.counts.critical,
      serious: input.counts.serious,
      moderate: input.counts.moderate,
      minor: input.counts.minor,
      passes: input.result.passes,
      incomplete: input.result.incomplete,
      inapplicable: input.result.inapplicable,
    },
    violations: input.result.violations.map((violation) => ({
      id: violation.id,
      impact: normalizeImpact(violation.impact),
      help: violation.help,
      description: violation.description,
      helpUrl: violation.helpUrl,
      nodeCount: violation.nodes.length,
      targets: violation.nodes.flatMap((node) => node.target),
    })),
  };
}

export function formatSuccessMessage(input: {
  score: number;
  totalRisks: number;
  counts: SeverityCounts;
  thresholdExceeded: boolean;
  failOn: FailOn;
}) {
  return [
    `AccessLint scan complete: score ${input.score}/100, ${input.totalRisks} risk${input.totalRisks === 1 ? "" : "s"}.`,
    `Critical ${input.counts.critical} | Serious ${input.counts.serious} | Moderate ${input.counts.moderate} | Minor ${input.counts.minor}.`,
    input.thresholdExceeded
      ? `The configured fail-on threshold (${input.failOn}) was exceeded.`
      : `The configured fail-on threshold (${input.failOn}) was not exceeded.`,
  ].join(" ");
}

function normalizeImpact(value: AxeViolation["impact"]): keyof SeverityCounts {
  return value === "critical" ||
    value === "serious" ||
    value === "moderate" ||
    value === "minor"
    ? value
    : "minor";
}
